Upkeep opportunity i189
uni-clouds/unicloud-frontwebapp pull request #204
Opened 2022-08-22 16:42 UTC by joaolavelino

Closes #189 

- Página de exibição da timeline das oportunidades de negócio

- Rotas para as exibições das informações
  - /customers/requests/ [opportunityid] /information (mostrar informações e atualização de status - conteúdo originalmente mostrado no modal)
  - /customers/requests/ [opportunityid] /timeline (mostrar a timeline da oportunidade - form para criar novos logs)

- Criar componentes da timeline:
  - Forumlário da criação e requisição
  - Componente da timeline (mostrando 5 últimos ou todos os logs)
  - Card da timeline (mostrando data, autor e mensagem resumida - podendo ser expandida ao clicar)

- Novo componente DynamicNavTabs - criado para considerar as subrotas dentro de uma rota dinâmica
- Atualização do componente Divider - criando a possibilidade colocar um espaçamento (prop spacing) para poder colcoar um espaço entre o conteúdo e o divider.
- Criação do hook useOneOpportunity, se comunicando com a rota /partner/get-one-opportunity

2022-08-25 13:41 UTC, ManuCoutinho requested changes
- atualizar branch com a `devlopment` e resolver conflitos
- antes do push rodar o comando `npm run lint`, verificar se há erros de lint e resolver em caso positivo

2022-08-25 18:52 UTC, ManuCoutinho requested changes
- no arquivo `public/locales/${lang}/customers-requests.json` há trechos duplicados em função de merge/conflito não resolvido;
- no component `src/components/Divider/index.tsx` alterar a `className` para atributos dinâmicos dentro do `./styles.ts`;
- no arquivo `./styles.ts` utilizar as cores definidas no `DefaultTheme`;
-  no arquivo `src/components/LogoLoader/index.tsx`: utilizar o component Image do Next/image para otimizar o arquivo estático;
- component `DynamicNavTab` -> criar um novo componente ou ou alterar o component NavTabs para receber novas funcinalidades. _Dificulta o controle de testes, a documentação e quebra a arquitetura a criação de mais de um componente por pasta_;
- o component `src/features/Forms/FormDetailsOpportunity/index.tsx` não precisa ser um form, já que não recebe nenhuma info do user. Usar elementos semânticos para evitar re-renders do componente. **vide erros de lint**
- no arquivo `src/features/Forms/FormHistoryLog/index.tsx`, utilizar as cores que vêem do hook `useTheme` no lugar de cores _hard code_;
- o componente `src/features/Forms/FormHistoryLog/index.tsx`precisa ser um form? Não identifiquei nenhuma action. Caso não precise ser, usar elementos semânticos;
- no arquivo `src/features/HeaderClients/index.tsx ` retirar a constante de links do componente;
- os componentes `src/features/HeaderOpportunity/index.tsx` e `src/features/HeaderClients/index.tsx ` têm as mesmas funções, utilizar apenas um provendo props dinâmicas;
- criar uma feature separada para o skeleton `src/features/OpportunityDetails/Skeletons.tsx`, segue a mesma lógica de arquitetura acima citada;
- verificar a tipagem das props no component `src/features/OpportunityDetails/index.tsx`;
- criar uma feature separada para o card e skeleton `src/features/OpportunityTimeline/`, segue a mesma lógica de arquitetura acima citada;
- no componente `CardOppTimeline` otimizar a utilização do styled components
- no component `src/pages/customers/requests/[opportunityid]/information.tsx`verificar se há necessidade de inclusão de permissão de rota e retirar o console.log;
- no components `Paper` incluir a prop=elevation para dar contraste nos tons de branco

👇🏾 **log de erros do eslint** _npm run lint_
```zsh
./src/features/Forms/FormDetailsOpportunity/index.tsx
58:6  Warning: React Hook useEffect has missing dependencies: 'expirationDateString' and 'setValue'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/features/NavigationTabs/DynamicNavigationTabs.tsx
20:6  Warning: React Hook useEffect has missing dependencies: 'opportunityid' and 'subroutes'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./src/features/OpportunityTimeline/index.tsx
35:6  Warning: React Hook useEffect has a missing dependency: 'shortList'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
```

2022-08-26 13:51 UTC, joaolavelino commented
Sobre o componente do header.. Se for para fazer um componente parametrizado para uso geral, podemos ver de fazer um upkeep nesse componente, porque todo o app tem esse componente...

2022-08-26 17:29 UTC, ManuCoutinho requested changes
- `console.log` esquecido no arquivo `src/components/DynamicNavTabs/index.tsx`
- log do npm lint
```zsh
./src/features/Forms/FormHistoryLog/index.tsx
13:10  Warning: 'toColorString' is defined but never used.  @typescript-eslint/no-unused-vars

./src/features/HeaderClients/index.tsx
12:8  Warning: 'icons' is defined but never used.  @typescript-eslint/no-unused-vars

./src/features/OpportunityInformation/index.tsx
2:10  Warning: 'useForm' is defined but never used.  @typescript-eslint/no-unused-vars
5:10  Warning: 'formatDate' is defined but never used.  @typescript-eslint/no-unused-vars
8:10  Warning: 'Input' is defined but never used.  @typescript-eslint/no-unused-vars
9:10  Warning: 'FieldText' is defined but never used.  @typescript-eslint/no-unused-vars
17:10  Warning: 'LogoLoader' is defined but never used.  @typescript-eslint/no-unused-vars

./src/features/OpportunityTimeline/styles.ts
2:10  Warning: 'CardStyleProps' is defined but never used.  @typescript-eslint/no-unused-vars

./src/pages/customers/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./src/pages/customers/requests/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./src/templates/Opportunities/Header.tsx
18:6  Error: 'Paper' is not defined.  react/jsx-no-undef
```
**Log de error de build***
```zsh
src/features/Forms/FormUpdateOpportunityStatus/index.tsx:31:13 - error TS2345: Argument of type 'void' is not assignable to parameter of type 'OneOpportunityType'.

31     setData(response)
               ~~~~~~~~

src/features/ModalDetailsRequest/index.tsx:2:10 - error TS2305: Module '"../OpportunityInformation"' has no exported member 'FormDetailsOpportunity'.

2 import { FormDetailsOpportunity } from '../OpportunityInformation'
           ~~~~~~~~~~~~~~~~~~~~~~

src/features/NavigationTabs/types.ts:3:3 - error TS2305: Module '"../../components/NavTabs/types"' has no exported member 'DynamicNavTabProps'.

3   DynamicNavTabProps
    ~~~~~~~~~~~~~~~~~~

src/features/OpportunityInformation/types.ts:5:8 - error TS2307: Cannot find module '../../../features/OpportunityTable/types' or its corresponding type declarations.

5 } from '../../../features/OpportunityTable/types'
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/features/OpportunityInformation/types.ts:6:36 - error TS2307: Cannot find module '../../OpportunityDetails/types' or its corresponding type declarations.

6 import { OneOpportunityType } from '../../OpportunityDetails/types'
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/features/OpportunityTimeline/styles.ts:2:10 - error TS2305: Module '"./types"' has no exported member 'CardStyleProps'.

2 import { CardStyleProps } from './types'
           ~~~~~~~~~~~~~~

src/templates/Opportunities/Header.tsx:18:6 - error TS2304: Cannot find name 'Paper'.

18     <Paper>
        ~~~~~

src/templates/Opportunities/Header.tsx:49:7 - error TS2304: Cannot find name 'Paper'.

49     </Paper>
         ~~~~~


Found 8 errors in 6 files.

Errors  Files
     1  src/features/Forms/FormUpdateOpportunityStatus/index.tsx:31
     1  src/features/ModalDetailsRequest/index.tsx:2
     1  src/features/NavigationTabs/types.ts:3
     2  src/features/OpportunityInformation/types.ts:5
     1  src/features/OpportunityTimeline/styles.ts:2
     2  src/templates/Opportunities/Header.tsx:18
```

2022-08-29 13:22 UTC, ManuCoutinho approved these changes
approved

2022-08-29 13:24 UTC, ManuCoutinho requested changes
Resolver conflitos ⚒️ 

public/locales/en/customers-requests.json
public/locales/es/customers-requests.json
public/locales/fr/customers-requests.json
public/locales/pt/customers-requests.json
src/features/Forms/FormCreateOpportunity/index.tsx
src/features/Forms/FormDetailsOpportunity/index.tsx
src/features/Forms/FormUpdateOpportunityStatus/index.tsx
src/features/HeaderClients/index.tsx
src/features/OpportunityTable/types.ts
src/templates/Opportunities/Header.tsx

2022-08-30 15:04 UTC, ManuCoutinho approved these changes
☑️

2022-08-30 15:05 UTC, merged

2022-09-14 14:38 UTC, fegma59 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: