Upkeep profile settings i207
uni-clouds/unicloud-frontwebapp pull request #208
Opened 2022-08-22 18:23 UTC by joaolavelino

- Acertar as rotas internas das páginas de profile e settings
- Acertar layout de 
- Acertar as traduções das páginas
- Acertar o input de tipo, que não tinham prop type.

Closes #207

2022-08-25 13:48 UTC, ManuCoutinho requested changes
- atualizar branch com a `devlopment` e resolver conflitos
- antes do push rodar o comando `npm run lint`, verificar se há erros de lint e resolver em caso positivo

2022-08-26 17:15 UTC, joaolavelino commented
Já passei o Lint e os chequei os conflitos com o devlopment

2022-08-26 17:50 UTC, ManuCoutinho requested changes
**Log de Lint**
```
/src/pages/customers/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./src/pages/customers/requests/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars
```
**Log de build**
```
./src/pages/customers/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars

./src/pages/customers/requests/index.tsx
8:10  Warning: 'useAccessLevelOne' is defined but never used.  @typescript-eslint/no-unused-vars
11:7  Warning: 'NotFound' is assigned a value but never used.  @typescript-eslint/no-unused-vars

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
☁  unicloud-frontwebapp [upkeep-profile-settings-i207] ⚡  npm run build

> broker-unicloud@0.0.1 build
> tsc && next build

src/features/PersonalInformation/index.tsx:13:38 - error TS2304: Cannot find name 'UserProfileProps'.

13 export const PersonalInformation: FC<UserProfileProps> = () => {
                                        ~~~~~~~~~~~~~~~~


Found 1 error in src/features/PersonalInformation/index.tsx:13
```

2022-08-29 13:53 UTC, ManuCoutinho reviewed
aprovado para realização de upkeeps

2022-08-29 13:54 UTC, merged

2022-09-14 14:39 UTC, fegma59 commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: