✨ Login V2
uni-clouds/unicloud-frontwebapp pull request #266
Opened 2022-09-06 12:15 UTC by ManuCoutinho

### primeiro acesso:

- [ ]  solicitar o e-mail ao usuário
    - [ ]  salvar o e-mail num *state* ou *store* e identificar o e-mail do usuário
        - [ ]  caso seja inválido, exibir mensagem de *bad news* 😈
        - [ ]  caso seja válido, renderizar a segunda tela solicitando:
            - [ ]  senha (campo obrigatório)
            - [ ]  idioma de preferência
                - [ ]  caso seja setado idioma, realizar o post em paralelo ao login
                - [ ]  setar manualmente na sessão atual o `locale=idiomaSelecionado`
                - [ ]  caso não seja enviado idioma:
                    - [ ]  verificar se o  🍪  `NEXT_LOCALE` existe no browser e deletar
        - [ ]  post para rota `/loginv2` utilizando o e-mail salvo no state e a senha solicitada
            - [ ]  caso o login seja mal sucedido, exibir mensagem de *bad news* 😈
            - [ ]  caso o login seja bem sucedido, redirecionar o usuário `route.push(🏡)`

---

### usuário não logado e/ou re-autenticação:

- [ ]  identificar se já tem cookies com `username` e `theme` setados e carregar
    - [ ]  setar mensagem de boas vindas de volta ao usuário e solicitar senha
    - [ ]  realizar autenticação com:
        - [ ]  carregamento das preferências de UI
        - [ ]  redirecionamento para rota 🏡
- [ ]  Deixar botão e/ou link para alterar o e-mail, caso o usuário deseje logar com outra conta

2022-09-15 17:31 UTC, joaolavelino commented
## Layout tela inicial
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190467324-8c9ff142-6ff2-4470-8670-aa9b16a27cee.png">
 - O form e o botão roxo estão desalinhados
 - O botão de escolha de idiomas me parece um pouco descolado do layout ali à direita. Ele está alinhado com o botão acima, mas como ele não tem o mesmo tamanho, nem a mesma altura, acaba que ficou um pouco solto ali. 
 - Não há indicação de que o EN significa o idioma em inglês. Não seria legal colocarmos uma frase: 'Select your language' ?
 - Eu tento mudar o idioma para, porém não muda aqui. Apenas na tela seguinte.
 
 - No inspect, na aba rede, tem uma chamada que deu erro para a logo192
 
 
 ## Passo 2
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190469336-ae6df33d-36c0-4ae3-b1b6-8fbb8816d369.png">
Ao colocar um email que não existe, ele me desejou boas vindas e apareceu a mensagem de trocar de conta.


<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190470543-b614a0c0-c6fa-4a51-b102-4a4693887c1a.png">
Ao entrar com o email correto ele não me dá a opção de voltar para entrar com outra conta. Se alguém está invadindo, já sabe que esse é um e-mail válido. Então imagino que seria melhor colocar o link de volta ao passo anterior nessa tela também.
Ele também não me dá olá nessa página... (#triste)



Ao acessar o meu email pessoal apareceu esse erro:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190471105-849ad885-352b-4593-84c8-96b6774bd5bb.png">

2022-09-15 17:33 UTC, joaolavelino requested changes
## Layout tela inicial
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190467324-8c9ff142-6ff2-4470-8670-aa9b16a27cee.png">
 - O form e o botão roxo estão desalinhados
 - O botão de escolha de idiomas me parece um pouco descolado do layout ali à direita. Ele está alinhado com o botão acima, mas como ele não tem o mesmo tamanho, nem a mesma altura, acaba que ficou um pouco solto ali. 
 - Não há indicação de que o EN significa o idioma em inglês. Não seria legal colocarmos uma frase: 'Select your language' ?
 - Eu tento mudar o idioma para, porém não muda aqui. Apenas na tela seguinte.
 
 - No inspect, na aba rede, tem uma chamada que deu erro para a logo192
 
 
 ## Passo 2
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190469336-ae6df33d-36c0-4ae3-b1b6-8fbb8816d369.png">
Ao colocar um email que não existe, ele me desejou boas vindas e apareceu a mensagem de trocar de conta.


<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190470543-b614a0c0-c6fa-4a51-b102-4a4693887c1a.png">
Ao entrar com o email correto ele não me dá a opção de voltar para entrar com outra conta. Se alguém está invadindo, já sabe que esse é um e-mail válido. Então imagino que seria melhor colocar o link de volta ao passo anterior nessa tela também.
Ele também não me dá olá nessa página... (#triste)


Ao acessar o meu email pessoal apareceu esse erro:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/84484002/190471105-849ad885-352b-4593-84c8-96b6774bd5bb.png">

2022-09-16 19:21 UTC, ManuCoutinho commented
Aguardando ajustes do backend
Issues
https://github.com/uni-clouds/back-unicloud/issues/184
https://github.com/uni-clouds/back-unicloud/issues/185

2022-09-20 16:18 UTC, joaolavelino requested changes
Olá Manu! Acho que está rolando aquele mesmo conflito com essa PR

2022-09-20 16:46 UTC, merged

2022-09-20 17:30 UTC, fegma59 commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: