Upkeep resources i27
uni-clouds/unicloud-frontwebapp pull request #295
Opened 2022-10-24 18:52 UTC by joaolavelino

- Form de criação de fabricantes e edição de fabricantes
   - Dentro de cada fabricante: 
     - Form de edição do fabricante, 
     - form de criação de família de produtos do fabricante, 
     - lista de gerenciamento de famílias de produtos do fabricante (edita nome, transfere de um fabricante para outro, apaga família)
   
 - Form de criação de Recursos (com campos novos)
   - Dentro de cada recurso: 
     - Form para edição do recurso
     - Apagar recurso

 - Criação de input para filtrar listas de recursos, tipos e fabricantes

 - Tratamento de erros através dos erros enviados pelo backend

2022-10-25 18:44 UTC, ManuCoutinho requested changes
#### Manter padrão *kebab case*  de escrita nos seguintes arquivos:

- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json

#### Retirar console.log dos seguintes arquivos: 

- src/features/Forms/FormCreateFamily/index.tsx
- src/features/Forms/FormCreateResources/index.tsx
- src/features/Forms/FormCreateResourcesFamily/index.tsx
- src/features/Forms/FormUpdateManufacturer/index.tsx
- src/features/Forms/FormUpdateResource/index.tsx
- src/features/Forms/FormUpdateResourceType/index.tsx
- src/features/Forms/FormUpdateResourcesFamily/index.tsx
- src/features/Resources/index.tsx
- src/features/ResourcesManufacturers/index.tsx
- src/features/ResourcesType/index.tsx


#### Correções: 

- src/features/Forms/FormCreateFamily/index.tsx -> atributo role inválido linha 60 / linha 41 msg de erro
- src/features/Forms/FormCreateFamily/types.ts -> types que não correspondem ao componente
- src/features/Forms/FormCreateResourceType/index.tsx -> bloco catch - verificar método e mensagens de error / 
- src/features/Forms/FormCreateResources/index.tsx -> bloco catch - verificar método e mensagens de error /  unificar o useEffect já que utilizam a mesma dependência para economizar processamento no re-render
- src/features/Forms/FormCreateResources/types.ts -> interface SelectBoxProps está sendo em outro componente, colocar no mesmo dir
- src/features/Forms/FormCreateResourcesFamily/index.tsx -> qual a finalidade do useEffect? / bloco catch - verificar método e mensagens de error / não localizei a key boom no arquivo common
- src/features/Forms/FormCreateResourcesManufacturer/index.tsx -> bloco catch - verificar método e mensagens de error /  
- src/features/Forms/FormListFilter/index.tsx -> type do input = search / role = searchbox / utilizar pseudo elemento para adicionar o icon dentro do input field e não ao lado / não há feedback visual para quando não há localização do item pesquisado / quando digita um valor e 'submita' a página dá full reload
- src/features/Forms/FormListFilter/styles.ts - não localizei h3 dentro do component / section é o elemento mais semântico neste caso? / Evitar utilização de medidas absolutas 
- src/features/Forms/FormUpdateManufacturer/index.tsx -> verificar bloco catch / atributo role = textbox / div com style in line
- src/features/Forms/FormUpdateResource/index.tsx -> primeiro useEffect sem finalidade / segundo e quinto useEffect sem as deps corretas/ const requestObject não poderia ser substituído por um switch ou reducer? / verificar todos atributos role
- src/features/Forms/FormUpdateResource/validation.ts -> os dois últimos itens não estão sendo validados
- src/features/Forms/FormUpdateResourceType/index.tsx -> ausência do método reset / toast error
- src/features/Forms/FormUpdateResourcesFamily/index.tsx -> bloco catch / atributo role 
- src/features/Forms/FormUpdateResourcesFamily/validation.ts -> os últimos campos não têm método de validação correta
- src/features/ListFilter/styles.ts -> framer motion está sendo importado, mas não é utilizado
- src/features/ResourceTypeManager/index.tsx -> bloco catch
- src/features/Resources/index.tsx -> bloco catch
- src/features/ResourcesFamiliesManager/index.tsx -> bloco catch
- src/features/ResourcesList/styles.ts -> uso de className
- src/features/ResourcesListManager/index.tsx - error msg
- src/components/Input/index.tsx -> prop list foi criada para?
- src/features/ResourcesManufacturers/index.tsx -> error msg
- src/features/ResourcesManufacturersManager/index.tsx -> error msg
- src/features/ResourcesType/index.tsx -> bloco catch
### UI
![Captura de tela de 2022-10-25 13-12-33](https://user-images.githubusercontent.com/80268705/197854836-a9dca2de-2f38-4602-ab6d-da56f98ae6be.png)

**para todas as telas**

![Captura de tela de 2022-10-25 12-10-21](https://user-images.githubusercontent.com/80268705/197855506-4433bc00-f55c-4666-920f-10ba1f357eef.png)
![Captura de tela de 2022-10-25 12-10-03](https://user-images.githubusercontent.com/80268705/197855953-e1bb1211-001c-42fa-a607-93da20462ada.png)

2022-11-03 17:33 UTC, joaolavelino commented
> #### Manter padrão _kebab case_ de escrita nos seguintes arquivos:
> * public/locales/en/common.json
> * public/locales/es/common.json
> * public/locales/pt/common.json
 **Nestes casos foi utilizado neste padrão diferente pois estas são as chamadas de erro vindas do Back-end. Para poder utilizar diretamente os erros enviados pelo back.** 
> 
> #### Retirar console.log dos seguintes arquivos:  
> * src/features/Forms/FormCreateFamily/index.tsx
> * src/features/Forms/FormCreateResources/index.tsx
> * src/features/Forms/FormCreateResourcesFamily/index.tsx
> * src/features/Forms/FormUpdateManufacturer/index.tsx
> * src/features/Forms/FormUpdateResource/index.tsx
> * src/features/Forms/FormUpdateResourceType/index.tsx
> * src/features/Forms/FormUpdateResourcesFamily/index.tsx
> * src/features/Resources/index.tsx
> * src/features/ResourcesManufacturers/index.tsx
> * src/features/ResourcesType/index.tsx
**Tudo removido**
> 
> #### Correções:
> * src/features/Forms/FormCreateFamily/index.tsx -> atributo role inválido linha 60 / linha 41 msg de erro **(atualizado para role='textbox')**
> * src/features/Forms/FormCreateFamily/types.ts -> types que não correspondem ao componente **(removidos, colocados junto ao componente)**
> * src/features/Forms/FormCreateResourceType/index.tsx -> bloco catch - verificar método e mensagens de error / **(coloquei no mesmo padrão de chamada de erro dos outros componentes)**
> * src/features/Forms/FormCreateResources/index.tsx -> bloco catch - verificar método e mensagens de error /  unificar o useEffect já que utilizam a mesma dependência para economizar processamento no re-render (** unificado o useEffect**)
> * src/features/Forms/FormCreateResources/types.ts -> interface SelectBoxProps está sendo em outro componente, colocar no mesmo dir **(está certo, eu apliquei no componente da pasta)** 
> * src/features/Forms/FormCreateResourcesFamily/index.tsx -> qual a finalidade do useEffect? / bloco catch - verificar método e mensagens de error / não localizei a key boom no arquivo common 
**(qual key voce nao encontrou - existe uma key: "already_exists_mfamily_this_name")**
> * src/features/Forms/FormCreateResourcesManufacturer/index.tsx -> bloco catch - verificar método e mensagens de error /
> * src/features/Forms/FormListFilter/index.tsx -> type do input = search / role = searchbox / utilizar pseudo elemento para adicionar o icon dentro do input field e não ao lado / não há feedback visual para quando não há localização do item pesquisado / quando digita um valor e 'submita' a página dá full reload

 -  in progress - 


> * src/features/Forms/FormListFilter/styles.ts - não localizei h3 dentro do component / section é o elemento mais semântico neste caso? / Evitar utilização de medidas absolutas
> * src/features/Forms/FormUpdateManufacturer/index.tsx -> verificar bloco catch / atributo role = textbox / div com style in line
> * src/features/Forms/FormUpdateResource/index.tsx -> primeiro useEffect sem finalidade / segundo e quinto useEffect sem as deps corretas/ const requestObject não poderia ser substituído por um switch ou reducer? / verificar todos atributos role
> * src/features/Forms/FormUpdateResource/validation.ts -> os dois últimos itens não estão sendo validados
> * src/features/Forms/FormUpdateResourceType/index.tsx -> ausência do método reset / toast error
> * src/features/Forms/FormUpdateResourcesFamily/index.tsx -> bloco catch / atributo role
> * src/features/Forms/FormUpdateResourcesFamily/validation.ts -> os últimos campos não têm método de validação correta
> * src/features/ListFilter/styles.ts -> framer motion está sendo importado, mas não é utilizado
> * src/features/ResourceTypeManager/index.tsx -> bloco catch
> * src/features/Resources/index.tsx -> bloco catch
> * src/features/ResourcesFamiliesManager/index.tsx -> bloco catch
> * src/features/ResourcesList/styles.ts -> uso de className
> * src/features/ResourcesListManager/index.tsx - error msg
> * src/components/Input/index.tsx -> prop list foi criada para?
> * src/features/ResourcesManufacturers/index.tsx -> error msg
> * src/features/ResourcesManufacturersManager/index.tsx -> error msg
> * src/features/ResourcesType/index.tsx -> bloco catch
> 
> ### UI
> ![Captura de tela de 2022-10-25 13-12-33](https://user-images.githubusercontent.com/80268705/197854836-a9dca2de-2f38-4602-ab6d-da56f98ae6be.png)
> 
> **para todas as telas**
> 
> ![Captura de tela de 2022-10-25 12-10-21](https://user-images.githubusercontent.com/80268705/197855506-4433bc00-f55c-4666-920f-10ba1f357eef.png) ![Captura de tela de 2022-10-25 12-10-03](https://user-images.githubusercontent.com/80268705/197855953-e1bb1211-001c-42fa-a607-93da20462ada.png)

2022-11-18 15:33 UTC, ManuCoutinho requested changes
- component com nomenclatura fora do padrão - src/components/Nothing Found/index.tsx (Pergunta: este componente não poderia ser mais abstrato? podendo receber diversos textos e ícones? Pq caso ele seja extremamente opinado não é um componente e não poderá ser reaproveitado amplamente.) Caso atualize, o nome deverá acompanhar a abstração
- console.log - src/features/Forms/FormUpdateResourcesFamily/index.tsx
- 
-Forms/FormCreateFamily; FormCreateResourceType;  -> toasts de error não está dependendo do log de error, mas de uma mensagem muito específica que pode não ocorrer e ainda assim existir um estado de error na request - tratar
- src/features/Forms/FormCreateResourcesFamily/index.tsx - linha 102
- src/features/Forms/FormListFilter/validation.ts -> sem mensagem de erro setada
- console.log - src/features/Forms/FormUpdateManufacturer/index.tsx
-  src/features/Forms/FormUpdateManufacturer/index.tsx -> role não podem ter hífen
- src/features/Forms/FormUpdateResource/index.tsx ->permanecem as obs anteriores referentes ao uso de switch e/ou reducer, o componente tem quase 500 linhas, ficando difícil a manutenção de coisas que não necessitariam estar, como blocos else para exibir console.log
-

2022-11-18 22:16 UTC, joaolavelino commented
> * component com nomenclatura fora do padrão - src/components/Nothing Found/index.tsx (Pergunta: este componente não poderia ser mais abstrato? podendo receber diversos textos e ícones? Pq caso ele seja extremamente opinado não é um componente e não poderá ser reaproveitado amplamente.) Caso atualize, o nome deverá acompanhar a abstração
> * console.log - src/features/Forms/FormUpdateResourcesFamily/index.tsx
> 
> -Forms/FormCreateFamily; FormCreateResourceType; -> toasts de error não está dependendo do log de error, mas de uma mensagem muito específica que pode não ocorrer e ainda assim existir um estado de error na request - tratar
> 
> * src/features/Forms/FormCreateResourcesFamily/index.tsx - linha 102
> * src/features/Forms/FormListFilter/validation.ts -> sem mensagem de erro setada
> * console.log - src/features/Forms/FormUpdateManufacturer/index.tsx
> * src/features/Forms/FormUpdateManufacturer/index.tsx -> role não podem ter hífen
> * src/features/Forms/FormUpdateResource/index.tsx ->permanecem as obs anteriores referentes ao uso de switch e/ou reducer, o componente tem quase 500 linhas, ficando difícil a manutenção de coisas que não necessitariam estar, como blocos else para exibir console.log

1 - created a generic component called IconMessage, with customizable props
2 - created an external function to replace that giant IF chain on src/features/Forms/FormUpdateResource/index.tsx
3 - removed the console.logs
4 - checked the catch blocks
5 - checked the validations

2022-11-22 15:53 UTC, ManuCoutinho requested changes
Component (src/components/IconMessage/index.tsx) - a propriedade size não está sendo utilizada

2022-11-22 16:50 UTC, ManuCoutinho approved these changes
Aprovado com as ressalvas das issues #297 e #312

2022-11-22 16:50 UTC, merged

2022-11-30 19:46 UTC, fegma59 commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: