Calc pdf export
uni-clouds/unicloud-frontwebapp pull request #305
Opened 2022-11-11 20:33 UTC by joaolavelino

Media queries to make it possible to print the quotations. 
Create a print button on the quotation details.

### Branch based on the Calc-fix-1 - merge that one first

Closes #304

2022-11-14 13:35 UTC, ManuCoutinho requested changes
_Na próxima vez, 'merge'  o novo recurso com a branch base, antes de abrir o pull request. Isto simplifica o processo, caso contrário vou ter que revisar os mesmos arquivos duas vezes._

Por favor, prossiga com sua funcionalidade, porém sem alterar nenhum arquivo da pasta Components. Eles já estão testados em outra branch (#306 ) e essas inserções causarão quebras nos testes, fazendo com  que eu volte e reescreva os testes, sem poder avançar na entrega.

2022-11-16 17:27 UTC, joaolavelino commented
Removidos media queries presentes em elementos da pasta components.   Estão concentrados nas features

2022-11-16 18:04 UTC, ManuCoutinho approved these changes

2022-11-16 18:04 UTC, merged

2022-11-30 19:46 UTC, fegma59 commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: