Calc taxes
uni-clouds/unicloud-frontwebapp pull request #309
Opened 2022-11-16 20:18 UTC by joaolavelino

Closes #307 

One more page on the calculator settings

Não tenho muita certeza em relação ao ícone usado no card.

2022-11-17 13:29 UTC, ManuCoutinho requested changes
Referente ao ícone, será alterado quando do refactor visual. Esse lembra desconto e imposto é acréscimo.

- Altera o ícone provisoriamente para: clarity:coin-bag-line
- Na inclusão de novos impostos force a fonte para uppercase (uniformização de layout)
- remover console.log
- useEffect em src/features/Forms/CalculatorSettingsFormEditTax/index.tsx necessita das dependências
- a toast taxes.unedited -> informa que não foi alterado, porém não indica o motivo (sempre que possível, indicar: causa, efeito e solução)

2022-11-17 17:06 UTC, joaolavelino commented
Referente ao ícone, será alterado quando do refactor visual. Esse lembra desconto e imposto é acréscimo.

- Altera o ícone provisoriamente para: clarity:coin-bag-line
**Trocado**

- Na inclusão de novos impostos force a fonte para uppercase (uniformização de layout)
**O input de nome do imposto está em maiúsculas, e o valor é enviado em maiúsculas**

- remover console.log
**removido**

- useEffect em src/features/Forms/CalculatorSettingsFormEditTax/index.tsx necessita das dependências
**adicionadas as dependências**

- a toast taxes.unedited -> informa que não foi alterado, porém não indica o motivo (sempre que possível, indicar: causa, efeito e solução)
**alterado o locale para ficar mais específico**

2022-11-17 17:17 UTC, ManuCoutinho requested changes
- src/features/Forms/CalculatorSettingsFormCreateTax/styles.ts - tem um `<form/>` dentro de outro  `<form/>` -> a fonte uppercase que me referi é na lista de exibição dos itens criados

2022-11-17 17:36 UTC, joaolavelino commented
> * src/features/Forms/CalculatorSettingsFormCreateTax/styles.ts - tem um `<form/>` dentro de outro  `<form/>` -> a fonte uppercase que me referi é na lista de exibição dos itens criados

Removi a logica do form e coloquei na lista

2022-11-18 12:35 UTC, ManuCoutinho approved these changes

2022-11-18 12:35 UTC, merged