Resources upkeep memory ratio
uni-clouds/unicloud-frontwebapp pull request #314
Opened 2022-11-23 13:28 UTC by joaolavelino

- Create useOneResouece hook 
 - Differentiate memory resource from the other resources (already on the list of #297
 - Protect the create and update resource forms from request failures
 - CRUD for ratios, only for memory resources
 - Icon Message size props

closes #308

2022-11-23 15:24 UTC, ManuCoutinho requested changes
- src/constants/endpoints.ts -> deixa só o endpoint no arquivo (constants/endpoints), a parte da query interpola no local em que está sendo utilizada, pq essa query pode mudar de acordo com a necessidade;
-  src/features/CalculatorFeature/util.ts -> linha 8 a verificação do length é comparado com ...?

2022-11-23 16:54 UTC, joaolavelino commented
> * src/constants/endpoints.ts -> deixa só o endpoint no arquivo (constants/endpoints), a parte da query interpola no local em que está sendo utilizada, pq essa query pode mudar de acordo com a necessidade;
> * src/features/CalculatorFeature/util.ts -> linha 8 a verificação do length é comparado com ...?

 - passei a key da query pra chamada. 
 - Na linha 8, eu coloquei a necessidade de ter os 7 elementos necessários para rodar a calculadora.

2022-11-23 17:05 UTC, ManuCoutinho approved these changes

2022-11-23 17:05 UTC, merged

2022-11-30 19:46 UTC, fegma59 commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on [GitHub release](https://github.com/uni-clouds/unicloud-frontwebapp/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: